import {
  BookOpen,
  Bell,
  Sparkles,
  Inbox,
  FileText,
  Receipt,
  Calendar,
  Ban,
  Banknote,
  Wallet,
  Coins,
  RefreshCw,
  DollarSign,
  TrendingUp,
  BarChart3,
  Shield,
  ShieldCheck,
  Users,
  UserCheck,
  Building2,
  Settings,
  CreditCard,
  FileArchive,
  Landmark,
  FileSpreadsheet,
  HelpCircle,
  Wand2,
  ShoppingCart,
  Box,
  Contact,
  Store,
  Lock,
  Warehouse,
  Calculator,
  ClipboardList,
  Activity,
  AlertTriangle,
  Zap,
  CalendarCheck,
  CalendarOff,
  Upload,
  Fingerprint,
  MapPin,
  LayoutTemplate,
  HardDrive,
  Package,
} from "lucide-react";
import type { ModuleConfig } from "@/components/layout/ModuleLayout";

export const MODULE_CONFIGS: Record<string, ModuleConfig> = {
  /* ═══════════════════════════════════════════
     SUPER ADMIN — Control Plane
     ═══════════════════════════════════════════ */
  superadmin: {
    id: "superadmin",
    label: "Control Plane",
    icon: Shield,
    color: "bg-muted-foreground",
    basePath: "/admin",
    sidebarItems: [
      { label: "Signup Requests", path: "/admin/signup-requests", icon: Inbox, group: "Onboarding" },
      { label: "Companies", path: "/admin/tenants", icon: Building2, group: "Onboarding" },
      { label: "Company Admins", path: "/admin/company-admins", icon: UserCheck, group: "Onboarding" },
      { label: "Users (Read-only)", path: "/admin/users", icon: Users, group: "Oversight" },
      { label: "System Analytics", path: "/admin/analytics", icon: Activity, group: "Oversight" },
      { label: "Subscriptions", path: "/admin/subscriptions", icon: CreditCard, group: "Oversight" },
      { label: "Storage", path: "/admin/storage", icon: HardDrive, group: "Oversight" },
      { label: "Audit Logs", path: "/admin/audit-logs", icon: Shield, group: "Logs" },
      { label: "Error Logs", path: "/admin/error-logs", icon: AlertTriangle, group: "Logs" },
    ],
  },

  /* ═══════════════════════════════════════════
     TENANT MODULES — Business Operations
     ═══════════════════════════════════════════ */
  accounting: {
    id: "accounting",
    label: "Accounting",
    icon: BookOpen,
    color: "bg-primary",
    basePath: "/accounting",
    sidebarItems: [
      { label: "Chart of Accounts", path: "/accounting/accounts", icon: BookOpen, group: "General Ledger" },
      { label: "Journal Entries", path: "/accounting/journals", icon: FileText, group: "General Ledger" },
      { label: "General Ledger", path: "/accounting/ledger", icon: Receipt, group: "General Ledger" },
      { label: "Trial Balance", path: "/accounting/trial-balance", icon: FileText, group: "General Ledger" },
      { label: "Statement Mapping", path: "/accounting/statement-mapping", icon: FileText, group: "General Ledger" },
      { label: "Receive Payment", path: "/accounting/receive-payment", icon: CreditCard, group: "Receivables" },
      { label: "Credit Notes", path: "/accounting/credit-notes", icon: Receipt, group: "Receivables" },
      { label: "AR Aging", path: "/accounting/ar-aging", icon: Calendar, group: "Receivables" },
      { label: "Vendors", path: "/accounting/vendors", icon: Store, group: "Payables" },
      { label: "Bills", path: "/accounting/bills", icon: FileText, group: "Payables" },
      { label: "Pay Bills", path: "/accounting/pay-bills", icon: CreditCard, group: "Payables" },
      { label: "Recurring Bills", path: "/accounting/recurring-bills", icon: RefreshCw, group: "Payables" },
      { label: "AP Aging", path: "/accounting/ap-aging", icon: Calendar, group: "Payables" },
      { label: "Bank & Cards", path: "/accounting/bank-accounts", icon: Landmark, group: "Cash & FX" },
      { label: "Foreign Exchange", path: "/accounting/foreign-exchange", icon: Coins, group: "Cash & FX" },
      { label: "Opening Balances", path: "/accounting/opening-balances", icon: Wallet, group: "Period Control" },
      { label: "Close OBE", path: "/accounting/close-obe", icon: Lock, group: "Period Control" },
      { label: "Fiscal Periods", path: "/accounting/fiscal-periods", icon: Calendar, group: "Period Control" },
      { label: "GL Verification", path: "/accounting/gl-verify", icon: Shield, group: "Period Control" },
    ],
  },
  banking: {
    id: "banking",
    label: "Banking",
    icon: Landmark,
    color: "bg-secondary",
    basePath: "/banking",
    sidebarItems: [
      { label: "Bank Reconciliation", path: "/banking/reconciliation", icon: Banknote, group: "Reconcile" },
      { label: "Bank Statement Import", path: "/banking/statement-import", icon: FileSpreadsheet, group: "Reconcile" },
      { label: "Import Rules", path: "/banking/import-rules", icon: Wand2, group: "Reconcile" },
      { label: "Suspense Clearing", path: "/banking/suspense-clearing", icon: HelpCircle, group: "Exceptions" },
      { label: "Held Rows", path: "/banking/held-rows", icon: Ban, group: "Exceptions" },
      { label: "Write Checks", path: "/banking/write-checks", icon: FileText, group: "Payments" },
      { label: "Petty Cash", path: "/banking/petty-cash", icon: Coins, group: "Payments" },
      { label: "Replenishments", path: "/banking/petty-cash/replenishments", icon: RefreshCw, group: "Payments" },
      { label: "Petty Cash Imports", path: "/banking/petty-cash/imports", icon: FileSpreadsheet, group: "Payments" },
      { label: "PC Account Types", path: "/banking/petty-cash/account-types", icon: Wand2, group: "Payments" },
      { label: "Petty Cash Suspense", path: "/banking/petty-cash/suspense", icon: HelpCircle, group: "Exceptions" },
    ],
  },
  sales: {
    id: "sales",
    label: "Sales",
    icon: ShoppingCart,
    color: "bg-[hsl(var(--success))]",
    basePath: "/sales",
    sidebarItems: [
      { label: "Quotes / Estimates", path: "/sales/quotes", icon: FileText, group: "Sell" },
      { label: "Invoices", path: "/sales/invoices", icon: Wallet, group: "Sell" },
      { label: "Recurring", path: "/sales/recurring-invoices", icon: RefreshCw, group: "Sell" },
      { label: "Invoice Templates", path: "/sales/invoice-templates", icon: LayoutTemplate, group: "Sell" },
      { label: "Receipts", path: "/sales/receipts", icon: Receipt, group: "Collect" },
      { label: "Deposits", path: "/sales/deposits", icon: Wallet, group: "Collect" },
      { label: "Reminders", path: "/sales/notifications", icon: Bell, group: "Collect" },
      { label: "Customers", path: "/sales/customers", icon: Contact, group: "Records" },
      { label: "Products", path: "/sales/products-taxes", icon: Package, group: "Records" },
      { label: "Discount Calculator", path: "/sales/discount-calculator", icon: Calculator, group: "Records" },
      { label: "Approvals", path: "/sales/approvals", icon: Shield, adminOnly: true, group: "Controls" },
      { label: "Number Register", path: "/sales/number-register", icon: ShieldCheck, adminOnly: true, group: "Controls" },
    ],
  },
  expenses: {
    id: "expenses",
    label: "Expenses",
    icon: Receipt,
    color: "bg-[hsl(var(--warning))]",
    basePath: "/expenses",
    sidebarItems: [
      { label: "Expense Tracker", path: "/expenses/tracker", icon: Banknote },
    ],
  },
  payroll: {
    id: "payroll",
    label: "Payroll",
    icon: DollarSign,
    color: "bg-[hsl(var(--info))]",
    basePath: "/payroll",
    sidebarItems: [
      { label: "Dashboard", path: "/payroll/dashboard", icon: Activity, group: "Overview" },
      { label: "Payroll Runs", path: "/payroll/runs", icon: DollarSign, group: "Pay Run" },
      { label: "Recurring Pay", path: "/payroll/recurring", icon: DollarSign, group: "Pay Run" },
      { label: "Liability Tracking", path: "/payroll/liabilities", icon: AlertTriangle, group: "Pay Run" },
      { label: "Employees", path: "/payroll/employees", icon: UserCheck, group: "People" },
      { label: "Loans & Advances", path: "/payroll/loans", icon: Banknote, group: "People" },
      { label: "Gratuity", path: "/payroll/gratuity", icon: Landmark, group: "People" },
      { label: "Attendance", path: "/payroll/attendance", icon: CalendarCheck, group: "Time & Attendance" },
      { label: "Leave", path: "/payroll/leave", icon: CalendarOff, group: "Time & Attendance" },
      { label: "Field Visits", path: "/payroll/field-visits", icon: MapPin, group: "Time & Attendance" },
      { label: "Import Attendance", path: "/payroll/attendance-import", icon: Upload, group: "Time & Attendance" },
      { label: "Device Linking", path: "/payroll/biometric-linking", icon: Fingerprint, group: "Time & Attendance" },
    ],
  },
  reports: {
    id: "reports",
    label: "Reports",
    icon: BarChart3,
    color: "bg-[hsl(var(--chart-5))]",
    basePath: "/reports",
    sidebarItems: [
      { label: "Financial Reports", path: "/reports/financial", icon: BarChart3, group: "Analysis" },
      { label: "Financial Analyst", path: "/reports/analyst", icon: Sparkles, group: "Analysis" },
      { label: "Asset Schedule", path: "/reports/financial?report=fixed-asset-schedule", icon: Warehouse, group: "Analysis" },
      { label: "Budgets", path: "/reports/budgets", icon: TrendingUp, group: "Planning" },
      { label: "Forecasting", path: "/reports/forecasting", icon: TrendingUp, group: "Planning" },
      { label: "Tax Center", path: "/tax", icon: Landmark, group: "Compliance" },
      { label: "Data Exports", path: "/reports/exports", icon: FileArchive, group: "Compliance" },
    ],
  },
  assets: {
    id: "assets",
    label: "Fixed Assets",
    icon: Warehouse,
    color: "bg-[hsl(var(--chart-4))]",
    basePath: "/assets",
    sidebarItems: [
      { label: "Asset Register", path: "/assets/register", icon: ClipboardList, group: "Register" },
      { label: "Add Asset", path: "/assets/new", icon: Warehouse, group: "Register" },
      { label: "Asset Categories", path: "/assets/categories", icon: Box, group: "Register" },
      { label: "Build from COA", path: "/assets/adopt", icon: Wand2, group: "Register" },
      { label: "Run Depreciation", path: "/assets/depreciation", icon: Calculator, group: "Processing" },
      { label: "Asset Reports", path: "/reports/financial?report=fixed-asset-schedule", icon: BarChart3, group: "Processing" },
    ],
  },
  tenantAdmin: {
    id: "tenantAdmin",
    label: "Settings",
    icon: Settings,
    color: "bg-muted-foreground",
    basePath: "/settings",
    sidebarItems: [
      { label: "General Settings", path: "/settings/general", icon: Settings, group: "Company" },
      { label: "Users", path: "/settings/users", icon: Users, group: "Company" },
      { label: "Account Mapping", path: "/settings/account-mapping", icon: Settings, group: "Accounting Setup" },
      { label: "Posting Profiles", path: "/settings/posting-profiles", icon: Zap, group: "Accounting Setup" },
      { label: "Payroll GL Mapping", path: "/settings/payroll-gl-mapping", icon: FileText, group: "Accounting Setup" },
      { label: "Tax Configuration", path: "/settings/tax", icon: Landmark, group: "Accounting Setup" },
      { label: "Classes & Locations", path: "/settings/classes-locations", icon: MapPin, group: "Accounting Setup" },
    ],
  },
};

export interface ModuleCard {
  id: string;
  label: string;
  description: string;
  icon: React.ElementType;
  color: string;
  path: string;
}

/** Module cards shown on the tenant home page */
export const HOME_MODULES: ModuleCard[] = [
  { id: "accounting", label: "Accounting", description: "Chart of accounts, journal entries, ledger & trial balance", icon: BookOpen, color: "bg-primary", path: "/accounting" },
  { id: "banking", label: "Banking", description: "Bank reconciliation, payment vouchers & petty cash", icon: Landmark, color: "bg-secondary", path: "/banking" },
  { id: "sales", label: "Sales", description: "Invoices, products, taxes & customer billing", icon: ShoppingCart, color: "bg-[hsl(var(--success))]", path: "/sales" },
  { id: "expenses", label: "Expenses", description: "Track and manage business expenses", icon: Receipt, color: "bg-[hsl(var(--warning))]", path: "/expenses" },
  { id: "payroll", label: "Payroll", description: "Process payroll, manage employees & pay schedules", icon: DollarSign, color: "bg-[hsl(var(--info))]", path: "/payroll" },
  { id: "reports", label: "Reports", description: "Financial reports, budgets & data exports", icon: BarChart3, color: "bg-[hsl(var(--chart-5))]", path: "/reports" },
  { id: "assets", label: "Fixed Assets", description: "Asset tracking, depreciation & disposal management", icon: Warehouse, color: "bg-[hsl(var(--chart-4))]", path: "/assets" },
  { id: "tenantAdmin", label: "Settings", description: "Users & system configuration", icon: Settings, color: "bg-muted-foreground", path: "/settings" },
];

/** Module cards shown on the Super Admin home page */
export const SUPER_ADMIN_MODULES: ModuleCard[] = [
  { id: "signup-requests", label: "Signup Requests", description: "Review and approve new company account applications", icon: Inbox, color: "bg-[hsl(var(--warning))]", path: "/admin/signup-requests" },
  { id: "tenants", label: "Companies", description: "Manage SaaS tenants and company provisioning", icon: Building2, color: "bg-primary", path: "/admin/tenants" },
  { id: "admins", label: "Company Admins", description: "Manage company administrator accounts", icon: UserCheck, color: "bg-secondary", path: "/admin/company-admins" },
  { id: "users", label: "Users", description: "Read-only overview of all system users", icon: Users, color: "bg-[hsl(var(--info))]", path: "/admin/users" },
  { id: "analytics", label: "System Analytics", description: "SaaS-level metrics and usage trends", icon: Activity, color: "bg-[hsl(var(--success))]", path: "/admin/analytics" },
  { id: "audit", label: "Audit Logs", description: "Track all system actions and changes", icon: Shield, color: "bg-[hsl(var(--warning))]", path: "/admin/audit-logs" },
  { id: "errors", label: "Error Logs", description: "System error monitoring and resolution", icon: AlertTriangle, color: "bg-destructive", path: "/admin/error-logs" },
  { id: "subscriptions", label: "Subscriptions", description: "Manage subscription plans", icon: CreditCard, color: "bg-muted-foreground", path: "/admin/subscriptions" },
];
